# Generated by Django 5.1.4 on 2026-02-03 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('url', 'URL'), ('file', 'Archivo')], max_length=10)),
                ('url', models.URLField(blank=True, null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='incidents/')),
                ('description', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Critico'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=10)),
                ('virustotal_result', models.JSONField(blank=True, null=True)),
                ('phishtank_result', models.JSONField(blank=True, null=True)),
                ('metadefender_result', models.JSONField(blank=True, null=True)),
                ('gemini_analysis', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('investigating', 'En Investigacion'), ('resolved', 'Resuelto')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-created_at'],
            },
        ),
    ]
