# Generated by Django 4.2.11 on 2025-12-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('threat_type', models.CharField(choices=[('PHISHING', 'Phishing'), ('MALWARE', 'Malware'), ('RANSOMWARE', 'Ransomware'), ('INGENIERÍA_SOCIAL', 'Ingeniería Social'), ('ACCESO_ANÓMALO', 'Acceso Anómalo'), ('ACCESO_NO_AUTORIZADO', 'Acceso no autorizado'), ('DOS', 'Ataque DoS'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('criticality', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRÍTICO', 'Crítico')], default='MEDIO', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('INVESTIGANDO', 'Investigando'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
