# Generated by Django 6.0 on 2025-12-29 20:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('analyst', 'Analista SOC'), ('employee', 'Empleado')], default='employee', help_text='Rol del usuario en el sistema', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario Personalizado',
                'verbose_name_plural': 'Usuarios Personalizados',
                'db_table': 'custom_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del incidente', max_length=255)),
                ('description', models.TextField(help_text='Descripción detallada del incidente')),
                ('incident_type', models.CharField(blank=True, default='', help_text='Tipo de incidente (phishing, malware, acceso_sospechoso, etc)', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], default='medium', help_text='Nivel de severidad del incidente', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('under_review', 'En Revisión'), ('resolved', 'Resuelto'), ('false_positive', 'Falsa Alarma'), ('in_progress', 'En Progreso')], default='new', help_text='Estado actual del incidente', max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Porcentaje de confianza de la detección (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('threat_type', models.CharField(default='unknown', help_text='Tipo de amenaza detectada por IA', max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de detección')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Fecha de resolución', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Notas de investigación')),
                ('log_source', models.CharField(blank=True, default='', help_text='Fuente del log (ej: syslog, firewall, aplicación)', max_length=255)),
                ('ip_source', models.GenericIPAddressField(blank=True, help_text='IP origen del evento', null=True)),
                ('ip_destination', models.GenericIPAddressField(blank=True, help_text='IP destino del evento', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario analista asignado para investigar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(help_text='Usuario que reportó el incidente', on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status', '-detected_at'], name='incidents_i_status_7c4c63_idx'), models.Index(fields=['severity', '-detected_at'], name='incidents_i_severit_13708b_idx'), models.Index(fields=['confidence'], name='incidents_i_confide_a93d44_idx')],
            },
        ),
    ]
