# Generated by Django 5.1.4 on 2026-02-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('analysis_type', models.CharField(choices=[('url', 'URL'), ('file', 'Archivo')], max_length=10)),
                ('url', models.URLField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('virustotal_result', models.JSONField(blank=True, null=True)),
                ('metadefender_result', models.JSONField(blank=True, null=True)),
                ('google_sb_result', models.JSONField(blank=True, null=True)),
                ('gemini_result', models.JSONField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=10, null=True)),
                ('positives', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hits', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cache de Analisis',
                'verbose_name_plural': 'Cache de Analisis',
                'ordering': ['-created_at'],
            },
        ),
    ]
