# Generated by Django 6.0 on 2025-12-28 17:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Incidente', 'verbose_name_plural': 'Incidentes'},
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ai_recommendation',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='analysis_result',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='criticality',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolved',
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Usuario asignado para investigar', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='Porcentaje de confianza de la detección (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='incident',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha y hora de detección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='ip_destination',
            field=models.GenericIPAddressField(blank=True, help_text='IP destino del evento', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='ip_source',
            field=models.GenericIPAddressField(blank=True, help_text='IP origen del evento', null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='log_source',
            field=models.CharField(blank=True, default='', help_text='Fuente del log (ej: syslog, firewall, aplicación)', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas de investigación'),
        ),
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], default='medium', help_text='Nivel de severidad del incidente', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='title',
            field=models.CharField(default='', help_text='Título del incidente', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(help_text='Descripción detallada del incidente'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de resolución', null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('under_review', 'En Revisión'), ('resolved', 'Resuelto'), ('false_positive', 'Falsa Alarma'), ('in_progress', 'En Progreso')], default='new', help_text='Estado actual del incidente', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='threat_type',
            field=models.CharField(default='unknown', help_text='Tipo de amenaza detectada por IA', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', '-detected_at'], name='incidents_i_status_7c4c63_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity', '-detected_at'], name='incidents_i_severit_13708b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['confidence'], name='incidents_i_confide_a93d44_idx'),
        ),
    ]
