# Generated by Django 6.0 on 2026-01-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='url',
            field=models.URLField(blank=True, help_text='URL o correo electrónico reportado como sospechoso', max_length=500, null=True),
        ),
    ]
