# Generated by Django 5.1.4 on 2026-02-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_analysiscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='analyst_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
