# Generated by Django 6.0 on 2026-01-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incident_gemini_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attached_file',
            field=models.FileField(blank=True, help_text='Archivo adjunto (captura, PDF, etc.)', null=True, upload_to='incident_files/'),
        ),
    ]
