# Generated by Django 5.1.4 on 2026-02-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incident_analysis_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('url', 'URL'), ('file', 'Archivo'), ('image', 'Imagen')], max_length=10),
        ),
    ]
