# Generated by Django 5.1.4 on 2026-02-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre de usuario ingresado', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP de origen', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Navegador y sistema operativo', null=True)),
                ('successful', models.BooleanField(default=False, help_text='¿Fue exitoso el inicio de sesión?')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del intento')),
            ],
            options={
                'verbose_name': 'Intento de Inicio de Sesión',
                'verbose_name_plural': 'Intentos de Inicio de Sesión',
                'ordering': ['-timestamp'],
            },
        ),
    ]
